# -*- coding: utf-8 -*-
"""CUMULATIVE_ABSOLUTE_EFFECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojNh7njE4iXA9HUxnCpV3nVuZ4WCvIsC
"""

!pip install causalimpact matplotlib pandas typing-extensions

import pandas as pd
con = pd.read_csv("/content/console_campaing.csv")
df = pd.read_csv("/content/console_campaing.csv", index_col=0)
df

print("SHAPE:", df.shape)
print(df.head())
print(df.isnull().sum())

regressors = [c for c in df.columns if c != 'console_sales']

data = df[['console_sales'] + regressors].astype(float)

data.dtypes

data = data.astype(float)

pre_period = [0, 83]
post_period = [84, len(df)-1]

import pandas as pd
from causalimpact import CausalImpact

ci = CausalImpact(data, pre_period, post_period,model_args={ 'period': 7})

#print(ci.summary())

"""Вам дан датасета с продажами маркетплейса за 2 года по ряду категорий. Поле console_sales содержит продажи в категории "Игровые приставки" для которой проводилась рекламная кампания. В данных периодичность — 1 неделя, **т.е. строка — это сумма по 7 дня. Запуск рекламы пришелся на 84-ю неделю.**"""